/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jaZrkzecm3e
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"

export function Accordian() {
  return (
    <Accordion className="w-full" collapsible type="single">
      <AccordionItem value="module-1">
        <AccordionTrigger>
          <h3 className="text-lg font-medium">Module 1</h3>
        </AccordionTrigger>
        <AccordionContent>
          <p className="text-gray-500 dark:text-gray-400">
            In this module, we will cover the fundamentals of web development, including HTML, CSS, and JavaScript.
            We'll start by learning how to structure web pages with HTML, style them with CSS, and add interactivity
            with JavaScript. By the end of this module, you'll have a solid understanding of the core technologies that
            power the web.
          </p>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
}
