/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1a2IpqKqVAm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Html } from "@react-email/html";
import { Text } from "@react-email/text";
import { Section } from "@react-email/section";
import { Container } from "@react-email/container";
import container from "postcss/lib/container";

export function CustomerEmailSuccess() {
  return (
    <Html>
    <Section >
      <Container >
    <div className="bg-white dark:bg-gray-950 rounded-lg p-6 max-w-[600px] mx-auto">
      <div className="flex flex-col items-center justify-center gap-6">
        <div className="flex flex-col items-center gap-2">
          <CircleCheckIcon className="text-green-500 w-12 h-12" />
          <div className="flex items-center gap-2">
            <Link href="#" prefetch={false}>
              <MountainIcon className="h-6 w-6" />
              <span className="sr-only">Acme Inc</span>
            </Link>
            <h1 className="text-2xl font-bold">Payment Successful</h1>
          </div>
          <p className="text-gray-500 dark:text-gray-400">Thank you for your purchase!</p>
        </div>
        <div className="flex flex-col gap-4 w-full">
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <img src="/placeholder.svg" width="40" height="40" alt="Course" className="rounded-md" />
                <div>
                  <h3 className="font-medium">Web Development Masterclass</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">by Acme Inc</p>
                </div>
              </div>
              <div className="text-right">
                <p className="font-medium">$99.99</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">Paid on June 18, 2024</p>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-4">
            <Button variant="outline">
              <DownloadIcon className="mr-2 h-4 w-4" />
              Download Receipt
            </Button>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-6 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              prefetch={false}
            >
              Go to Course Dashboard
            </Link>
          </div>
        </div>
      </div>
    </div>
    </Container>
    </Section>
    </Html>
  )
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function DownloadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
