/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KI4nDA9VGby
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Profile() {
  return (
    <main className="flex-1 bg-gray-100 dark:bg-gray-800">
      <div className="container grid grid-cols-1 gap-8 py-8 md:grid-cols-2 lg:grid-cols-3">
        <div className="col-span-1 rounded-lg bg-white p-6 shadow-sm dark:bg-gray-950">
          <div className="flex items-center gap-4">
            <Avatar className="h-12 w-12">
              <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <div>
              <h3 className="text-lg font-semibold">John Doe</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">john.doe@example.com</p>
            </div>
          </div>
          <div className="mt-6 space-y-4">
            <div className="grid gap-2">
              <Label htmlFor="name">Name</Label>
              <Input defaultValue="John Doe" id="name" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input defaultValue="john.doe@example.com" id="email" type="email" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="bio">Bio</Label>
              <Textarea
                className="min-h-[100px]"
                defaultValue="I am a web developer with a passion for building beautiful and functional websites."
                id="bio"
              />
            </div>
            <Button className="w-full">Update Profile</Button>
          </div>
        </div>
      </div>
    </main>
  )
}
