/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BMJPoeiyM6L
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client";

import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import { FormEvent, useEffect, useState } from "react"
import { account } from "@/lib/server/appwrite"
import { ToastAction } from "@/components/ui/toast"
import { useToast } from "@/components/ui/use-toast"
import { useRouter } from "next/navigation"; // Change this line

export function SignIn() {
  const router = useRouter();

  const [email, setemail] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast()

  useEffect(() => {
    const checkSession = async () => {
      try {
        const response = await account.get();
        if (response) {
          router.push('/dashboard/user'); // Redirect to dashboard if already signed in
        }
      } catch (error) {
        // User is not signed in or session is invalid
      }
    };

    checkSession();
  }, [router]);



  const handleSignIn = async (event: FormEvent) => {
    event.preventDefault();
    try {

      const response = await account.createEmailPasswordSession(email, password);
      toast({
        description: "Login Successful.",
      })

      router.push('/dashboard/user'); // Redirect to dashboard
    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Your email and password does not matches please try again",
        action: <ToastAction altText="Try again">Try again</ToastAction>,
      })
      setError(error.message || 'An error occurred. Please try again.');
      console.error(error);
    }
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="w-full max-w-md space-y-8">
        <div>
          <img
            alt="Company Logo"
            className="mx-auto"
            height={48}
            src="/images/mn-top-security-logo-new-black.png"
            style={{
              aspectRatio: '48/48',
              objectFit: 'cover',
            }}
            width={48}
          />
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign in to your account</h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            Or
            <Link className="font-medium text-indigo-600 hover:text-indigo-500" href="/signup">
              sign up for a new account
            </Link>
          </p>
        </div>
        {error && (
          <div className="rounded-md bg-red-50 p-4">
            <div className="flex">
              <div className="ml-3">
                <h3 className="text-sm font-medium text-red-800">{error}</h3>
              </div>
            </div>
          </div>
        )}
        <form className="space-y-6" onSubmit={handleSignIn}>
          <div>
            <Label className="sr-only" htmlFor="email">
              email
            </Label>
            <Input
              autoComplete="email"
              className="relative block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
              id="email"
              name="email"
              placeholder="email"
              required
              type="email"
              value={email}
              onChange={(e) => setemail(e.target.value)}
            />
          </div>
          <div>
            <Label className="sr-only" htmlFor="password">
              Password
            </Label>
            <Input
              autoComplete="current-password"
              className="relative block w-full appearance-none rounded-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
              id="password"
              name="password"
              placeholder="Password"
              required
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Checkbox
                className="h-4 w-4 rounded text-indigo-600 focus:ring-indigo-500"
                id="remember-me"
                name="remember-me"
              />
              <Label className="ml-2 block text-sm text-gray-900" htmlFor="remember-me">
                Remember me
              </Label>
            </div>
            <div className="text-sm">
              <Link className="font-medium text-indigo-600 hover:text-indigo-500" href="#">
                Forgot your password?
              </Link>
            </div>
          </div>
          <div>
            <Button
              className="group relative flex w-full justify-center rounded-md bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
              type="submit"
            >
              Sign in
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
